version: 2

sources:
  - name: RAW
    database: DOOR2DOOR_DWH
    tables:
      - name: vehicle_iot_data
        description: Contains iot events emitted from vehicles.
        columns:
          - name: VALUE
            description: Event properties.